### ISSUE TITLE
Broken link in day 22

### ISSUE THREAD

**Issue by martincmartin** [tginsberg/advent-2024-kotlin#1]
Hey Todd, I wanted to check out your blog post for day 22, since my solution for part 2 took something like 10 minutes to run.  Your link ends in `/22/`, but the actual blog post ends in `/day22/`.

Thanks again for the code & posts!

**Comment by tginsberg** [comment]
@martincmartin Thanks! I actually had days 9 through 24 broken due to copy/paste errors (now the dirty secret that I don't use a template is out)!. Thanks for the report, and I'm glad you found my code and blog useful. :)
